### PR TITLE
OSX Build Compatibility

### PR DESCRIPTION
**Pull request by wilfchun**
Adjusted makefiles such that the code can now be built on an apple silicone device.
Tested on: Apple MacBook air M2
Code has also been tested on ubuntu system to confirm it still builds correctly

Additionally I have added a gitignore file preloaded with standard c++ and Cmake ignores.
This should make further development easier and prevent developers uploading build files.

### CODE REVIEW

**Review by davefavismortlock — COMMENTED** [review]
This looks fine to me, Wilf. Thank you very much! And apologies for being slow in responding. However I'll wait until I've made a package from the 1.2.0 code, and I've pushed 1.2.1 onto GitHub, before I merge your changes. Does that seem OK to you? Dave

**Comment by davefavismortlock** [comment]
Hi Wilf -- "This branch has conflicts that must be resolved", the thing is that the conflict is in a binary file: src/lib/libcshore.so Any idea how we deal with this? Dave

**Comment by wilfchun** [comment]
> Hi Wilf -- "This branch has conflicts that must be resolved", the thing is that the conflict is in a binary file: src/lib/libcshore.so Any idea how we deal with this? Dave

Should we just delete the file from the repository and add it to the .gitignore?
If I understand correctly this file should be produced when Cshore is built, which is in turn triggered by the build of CoastalME

**Review by davefavismortlock — APPROVED** [review]

**Comment by davefavismortlock** [comment]
Merged

**Pull request closed without merging**
